version: "3.3"
services:
  pgsql:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./database-pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
